### ISSUE TITLE
Button does not become "unhovered" if it's rerendered on click

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#82] opened 2017-11-24 13:03 UTC
![_1](https://user-images.githubusercontent.com/873919/33211669-976e3048-d130-11e7-86cb-0ecb7f9e99e5.gif)

Here clicking on the button causes sending a message (Elmish), which causes re-rendering the button. After that it's forever in "hovered" state until it's re-rendered again (by another event, not by clicking).

**Comment by MangelMaxime** [comment] 2017-11-24 13:31
Can you please give reproduction so I can understand what's happening ?

**Comment by vasily-kirichenko** [comment] 2017-11-24 13:48
```fsharp
Box.box' []
      [ Level.level []
          [ Level.left []
              [ yield Level.item [] [ str "Status" ]

                yield
                  Level.item []
                    [ Control.control_div []
                        [ let caption, tooltip, stateToSwitch, option =
                            match app.State with
                            | AppState.Enabled ->
                                "turn off",
                                sprintf "Turn off all %s instances" app.Name,
                                AppState.Disabled,
                                Button.isDanger

                            | AppState.Disabled ->
                                "turn on",
                                sprintf "Turn on all (%d) %s instances" app.ConfiguredInstanceCount app.Name,
                                AppState.Enabled,
                                Button.isSuccess
                          yield
                            Button.button_btn
                              [ Button.props [Id "changeStateButton" ]
                                Button.isOutlined
                                option
                                Button.props [ Tooltip.dataTooltip tooltip ]
                                Button.customClass Tooltip.ClassName
                                // SetAppState eventually (< 1 seconds) changes app.State
                                Button.onClick (fun _ -> dispatch (Msg.SetAppState (host, app.Name, stateToSwitch))) ]
                              [ str caption ]
                        ]
                    ]
              ]
          ]
      ]
```

**Comment by MangelMaxime** [comment] 2017-11-24 14:10
Sorry, I will need a view + update + model to repro it.

I can't reproduce this behavior in my app. I have a button, which when clicked generate an event and cause a re-rendering and it's state is correct.

Can you please tell me if the behavior in the extra section [here](https://mangelmaxime.github.io/Fulma/#fulma/elements/button) work as expected for you ?

**Comment by MangelMaxime** [comment] 2017-11-24 18:12
For reference, this is happening when we are using: `button_btn`.

If we use `button_a` then the behavior is correct. It's probably something related to how HTML and CSS works. Not much to be done on Fulma side so I am closing this issue.

**Closed by MangelMaxime** 2017-11-24 18:12 UTC
